### ISSUE TITLE
String and Subtype issues

### ISSUE THREAD

**Issue by Kereemgd** [BrendanParmer/NodeToPython#124]
The addon currently exports gamma_socket.subtype as an empty string ("") instead of "NONE". Additionally, there's a string handling issue with the frame.label properties. By exporting and printing the material to another Blender file, you can recreate and diagnose these errors.

https://www.mediafire.com/file/czrnfhpdm3bkus3/marble-generator_fd43fd04-2a08-4cbd-8199-9d3557a280e9.blend/file

Github does not allow directly uploading ".blend" files. 

Big thanks for this great addon.

**Comment by BrendanParmer** [comment]
Thanks for spotting these! 

The gamma socket one seems like a bug with Blender. The `subtype` property is set to `''` rather than `NONE` for some reason. I've submitted [a bug report](https://projects.blender.org/blender/blender/issues/126535) to Blender on the issue. Regardless, NodeToPython will just assume it's `NONE` and ignore it with v3.2.1

**Comment by BrendanParmer** [comment]
Fix for the bug report with [this PR](https://projects.blender.org/blender/blender/pulls/126679), looks like it's targeting the next Blender 4.2 LTS release
