### ISSUE TITLE
Object has no attribute 'interface' in Blender 3.6

### ISSUE THREAD

**Issue by hkunz** [BrendanParmer/NodeToPython#94]
The script generated is incorrect. It uses an attribute 'interface' that does not exist in blender.

`geometry_socket = voxelize.interface.new_socket`

Notice that there is a misplaced 'interface' attribute that blender does not recognize.

Python: Traceback (most recent call last):
  File "\Text", line 202, in <module>
  File "\Text", line 11, in voxelpositions_node_group
AttributeError: 'GeometryNodeTree' object has no attribute 'interface'

**Comment by BrendanParmer** [comment]
Hi @hkunz. It seems like your script was generated with the Blender 4.0 `NodeTree` structure, which uses a [new API](https://developer.blender.org/docs/release_notes/4.0/python_api/#node-groups) with an `interface` attribute for creation of new sockets and panels.

Currently scripts generated by NTP with Blender versions before v4.0 aren't forwards compatible with versions after v4.0, and scripts generated after v4.0 aren't backwards compatible with versions before v4.0. At some point I'd like to introduce a feature to allow for optional backwards/forwards compatibility, so that (unless editing node tree sockets) you wouldn't have to maintain code in two spots; I might prioritize this for NTP v3.1. 

As a workaround right now, you can do something like
```python3
if bpy.app.version < (4, 0, 0):
    # Pasted script generated before Blender v4.0
    ...
else:
    # Pasted script generated after Blender v4.0
    ...
```

**Comment by BrendanParmer** [comment]
You can still use NodeToPython 3.0.x to generate scripts for Blender pre-4.0, but they won't have forward compatibility to 4.0+ without doing the workaround. I'm not aware of any projects that generate truly cross-compatible Python scripts from node groups currently

**Comment by BrendanParmer** [comment]
Cross-compatibility to be added with #95

**Comment by hkunz** [comment]
hey thank you very much. btw great stuff you made. i was thinking of making something like this then i realized there are probably libraries already out there and oh yes i found this!

**Comment by hkunz** [comment]
Thanks alot it works perfectly. but i think there is a bug but im not exactly sure what it is. its related to this thread https://blender.stackexchange.com/questions/314386/python-generated-geonodes-setup-not-behaving-the-same-with-the-original-geonode
